export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const FETCH_ALL_LOCATION = 'FETCH_ALL_LOCATION';
export const FETCH_USER_LOCATION = 'FETCH_USER_LOCATION';
export const CREATE_USER_LOCATION = 'CREATE_USER_LOCATION';
export const CREATE_USER_LOCATION_FAILED = 'CREATE_USER_LOCATION_FAILED';
export const FETCH_USER_LOCATION_FAILED ='FETCH_USER_LOCATION_FAILED';
export const FETCH_ALL_LOCATION_FAILED = 'FETCH_ALL_LOCATION_FAILED';
export const LOADING_LOCATIONS = 'LOADING_LOCATIONS';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
